CourseProjectItr/Models/User.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace CourseProjectItr.Models
{
    public class User : IdentityUser
    {
        public static object Identity { get; internal set; }
        public string NickName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public DateTime RegisterDate { get; set; }
        public DateTime LastLogin { get; set; }
    }
}

CourseProjectItr/Controllers/CollectionController.cs
using CourseProjectItr.Models;
using CourseProjectItr.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CourseProjectItr.Controllers
{
    public class CollectionController : Controller
    {
        private ApplicationContext db;
        private readonly IStringLocalizer<CollectionController> _localizer;
        private readonly ICloudStorage _cloudStorage;
        private readonly UserManager<User> _userManager;
        public CollectionController(ApplicationContext context, ICloudStorage cloudStorage, IStringLocalizer<CollectionController> localizer, UserManager<User> userManager)
        {
            db = context;
            _cloudStorage = cloudStorage;
            _localizer = localizer;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Collection(string userID)
        {
            ViewBag.UserID = userID;
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> ItemList(string collectionId, string userID)
        {
            Collections collection = await db.Collections.FirstOrDefaultAsync(c => c.Id == collectionId);
            User user = await _userManager.FindByIdAsync(collection.UserId);
            ViewBag.Collection = collection;
            ViewBag.UserID = userID;
            ViewBag.Creator = user.UserName;
            var itemsID = db.ItemsOfCollections.Where(i => i.CollectionId == collectionId).Select(it => it.Id).ToList();
            List<Items> itemsList = new List<Items>();
            if (itemsID != null && itemsID.Count != 0)
            {
                foreach(var id in itemsID)
                {
                    itemsList.Add(await db.Items.FirstOrDefaultAsync(c => c.Id == id));
                }
                return View(itemsList);
            }
            return View();
        }
        [HttpGet]
        public IActionResult Index()
        {
            var coll = db.Collections.ToList();
            return View(coll);
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "author, admin, user")]
        public async Task<IActionResult> Collection(CollectionViewModel model)
        {
                Collections collections = await db.Collections.FirstOrDefaultAsync(c => c.Name == model.Name);
                if(collections == null && model.UserId != null)
                {
                    collections = new Collections
                    {
                        UserId = model.UserId,
                        Name = model.Name,
                        Theme = model.Theme,
                        Review = model.Review,
                        One = model.One,
                        Second = model.Second,
                        Third = model.Third,
                        NumberOne = model.NumberOne,
                        NumberSecond = model.NumberSecond,
                        NumberThird = model.NumberThird,
                        OneText = model.OneText,
                        SecondText = model.SecondText,
                        ThirdText = model.ThirdText,
                        CheckBox1 = model.CheckBox1,
                        CheckBox2 = model.CheckBox2,
                        CheckBox3 = model.CheckBox3,
                        Time1 = model.Time1,
                        Time2 = model.Time2,
                        Time3 = model.Time3
                    };
                if(model.ImageFile != null)
                {
                    await UploadFile(model, collections);
                }
                    db.Collections.Add(collections);
                    await db.SaveChangesAsync();
                User user = await db.Users.FindAsync(model.UserId);
                    return RedirectToAction("Index", "User", new {user.UserName });
                }
            return View(model);
        }
        private async Task UploadFile(CollectionViewModel model, Collections collection)
        {
            string fileNameForStorage = FormFileName(model.Name, model.ImageFile.FileName);
            collection.ImageUrl = await _cloudStorage.UploadFileAsync(model.ImageFile, fileNameForStorage);
            collection.ImageStorageName = fileNameForStorage;
        }

        private static string FormFileName(string title, string fileName)
        {
            var fileExtension = Path.GetExtension(fileName);
            var fileNameForStorage = $"{title}-{DateTime.Now.ToString("yyyyMMddHHmmss")}{fileExtension}";
            return fileNameForStorage;
        }

        public async Task<IActionResult> Edit(string id, string userName)
        {
            Collections collection = await db.Collections.FindAsync(id);
            User user = await _userManager.FindByNameAsync(userName);

            if (collection == null)
            {
                return NotFound();
            }
            if(collection.UserId == user.Id)
            {
                EditCollectionViewModel model = new EditCollectionViewModel
                {
                    Id = collection.Id,
                    UserId = collection.UserId,
                    Review = collection.Review,
                    Name = collection.Name,
                    Theme = collection.Theme,
                    ImageUrl = collection.ImageUrl,
                    ImageStorageName = collection.ImageStorageName,
                    OneText = collection.OneText,
                    SecondText = collection.SecondText,
                    ThirdText = collection.ThirdText,
                    CheckBox1 = collection.CheckBox1,
                    CheckBox2 = collection.CheckBox2,
                    CheckBox3 = collection.CheckBox3,
                    Time1 = collection.Time1,
                    Time2 = collection.Time2,
                    Time3 = collection.Time3,
                    One = collection.One,
                    Second = collection.Second,
                    Third = collection.Third,
                    NumberOne = collection.NumberOne,
                    NumberSecond = collection.NumberSecond,
                    NumberThird = collection.NumberThird
                };
                return View(model);
            }
            else
            {
                ModelState.AddModelError("", "You cant edit this collection");
                return View();
            }
        }

        [HttpPost]
        [Authorize(Roles = "author, admin, user")]
        public async Task<IActionResult> Edit(EditCollectionViewModel model)
        {
            if (ModelState.IsValid)
            {
                Collections collection = await db.Collections.FirstOrDefaultAsync(c => c.Name == model.Name);
                if (collection != null)
                {
                    if (model.ImageFile != null)
                    {
                        if (collection.ImageStorageName != null)
                        {
                            await _cloudStorage.DeleteFileAsync(collection.ImageStorageName);
                        }

                        string fileNameForStorage = FormFileName(model.Name, model.ImageFile.FileName);
                        collection.ImageUrl = await _cloudStorage.UploadFileAsync(model.ImageFile, fileNameForStorage);
                        collection.ImageStorageName = fileNameForStorage;
                    }
                    collection.Review = model.Review;
                    collection.Name = model.Name;
                    collection.Theme = model.Theme;
                    collection.OneText = model.OneText;
                    collection.SecondText = model.SecondText;
                    collection.ThirdText = model.ThirdText;
                    collection.CheckBox1 = model.CheckBox1;
                    collection.CheckBox2 = model.CheckBox2;
                    collection.CheckBox3 = model.CheckBox3;
                    collection.Time1 = model.Time1;
                    collection.Time2 = model.Time2;
                    collection.Time3 = model.Time3;
                    collection.One = model.One;
                    collection.Second = model.Second;
                    collection.Third = model.Third;
                    collection.NumberOne = model.NumberOne;
                    collection.NumberSecond = model.NumberSecond;
                    collection.NumberThird = model.NumberThird;

                    db.Collections.Update(collection);
                    await db.SaveChangesAsync();
                    User user = await db.Users.FindAsync(collection.UserId);
                    return RedirectToAction("Index", "User", new { user.UserName });
                }
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "author, admin, user")]
        public async Task<IActionResult> Delete(string collectionId, string userName)
        {
            Collections collection = await db.Collections.FindAsync(collectionId);

            if (collection != null)
            {
                var items = db.ItemsOfCollections.Where(i => i.CollectionId == collectionId).Select(i => i.Id).ToList();
                foreach(var i in items)
                {

CourseProjectItr/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CourseProjectItr.Models;
using CourseProjectItr.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CourseProjectItr.Controllers
{
    public class UserController : Controller
    {
        UserManager<User> _userManager;
        ApplicationContext db;

        public UserController(UserManager<User> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            db = context;
        }
        [HttpGet]
        [Authorize(Roles = "author, admin")]
        public IActionResult AdminList()
        {
            return View(_userManager.Users.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Index(string userName)
        {
            if (userName != null)
            {
                User user = await _userManager.FindByNameAsync(userName);
                if(user != null)
                {
                    var roleIdentity = await _userManager.GetRolesAsync(user);
                    ViewBag.Role = roleIdentity[0];
                    ViewBag.Collection = db.Collections.Where(c => c.UserId == user.Id).ToList();
                }
                return View(user);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Age = user.Age, FirstName = user.FirstName, LastName = user.LastName, NickName = user.NickName };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Age = model.Age;
                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    user.NickName = model.NickName;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "User", new { user.UserName });
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult<Likes>> Like([FromBody]LikeViewModel model)
        {
            Likes like = await db.Likes.FindAsync(model.ItemID);
            if (like != null && model.Choise == "true")
            {
                like.Like++;
                db.Likes.Update(like);
                await db.SaveChangesAsync();
                return Ok(like);
            }
            else if (like != null && model.Choise == "false")
            {
                like.Like--;
                db.Likes.Update(like);
                await db.SaveChangesAsync();
                return Ok(like);
            }
            return null;
        }
        [HttpPost]
        public async Task<ActionResult<Comments>> Comment([FromBody]CommentViewModel model)
        {
            User user = await db.Users.FirstOrDefaultAsync(u => u.UserName == model.UserName);
            Items item = await db.Items.FirstOrDefaultAsync(i => i.Id == model.ItemID);
            List<Comments> count = db.Comments.Where(c => c.ItemId == model.ItemID).ToList();
            if(user != null && item != null)
            {
                Comments comment = new Comments { Comment = model.Comment, ItemId = model.ItemID, UserId = user.Id, UserName = user.NickName, Number = count.Count() };
                db.Comments.Add(comment);
                await db.SaveChangesAsync();
                return Ok(comment);
            }
            return null;
        }
    }
}

CourseProjectItr/Views/User/AdminList.cshtml
@model IEnumerable<CourseProjectItr.Models.User>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewBag.Title = Localizer["AdminPanel"];
}
<div class="container">
    @if (User.Identity.IsAuthenticated)
    {
    <div class="container">
        <nav class="navbar navbar-dark bg-dark">
            <form>
                <button class="btn btn-success" type="button" onclick="sendDataUn()">@Localizer["Unblock"]</button>
                <button class="btn btn-warning" type="button" onclick="sendDataB()">@Localizer["Block"]</button>
                <button class="btn btn-danger" type="button" onclick="sendDataD()">@Localizer["Delete"]</button>
                <button class="btn btn-danger" type="button" onclick="sendDataAd()">@Localizer["Admin"]</button>
            </form>
        </nav>

        <table class="table table-striped table-dark">
            <tr>
                <th scope="col">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="checkAll" onclick='addAllItem()' unchecked>
                        <label class="custom-control-label" for="checkAll" name="labelAll">All</label>
                    </div>
                </th>
                <th scope="col">@Localizer["Id"]</th>
                <th scope="col">@Localizer["Name"]</th>
                <th scope="col">@Localizer["Email"]</th>
                <th scope="col">@Localizer["Register"]</th>
                <th scope="col">@Localizer["LastLogin"]</th>
            </tr>
            <tbody>
                @foreach (var user in Model)
                {
                <tr>
                    <th scope="row">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="@user.Id" name="users" unchecked>
                            <label class="custom-control-label" for="@user.Id"></label>
                        </div>
                    </th>
                    <td>@user.Id</td>
                    <td><a asp-action="Index" asp-route-userName="@user.UserName">@user.FirstName @user.LastName</a></td>
                    <td>@user.Email</td>
                    <td>@user.RegisterDate</td>
                    <td>@user.LastLogin</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    }
    </div>

CourseProjectItr/Views/User/Edit.cshtml
@model CourseProjectItr.ViewModels.EditUserViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewBag.Title = Localizer["Title"];
}
<div class="container">
    <form asp-action="Edit" asp-controller="User">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <input type="hidden" asp-for="Id" />
        </div>
        <div class="form-group">
            <label asp-for="Email" class="control-label">@Localizer["Email"]</label>
            <input type="text" asp-for="Email" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Age" class="control-label">@Localizer["Age"]</label>
            <input type="number" asp-for="Age" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="NickName" class="control-label">@Localizer["NickName"]</label>
            <input type="text" asp-for="NickName" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="FirstName" class="control-label">@Localizer["FirstName"]</label>
            <input type="text" asp-for="FirstName" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label">@Localizer["LastName"]</label>
            <input type="text" asp-for="LastName" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="@Localizer["Save"]" class="btn btn-outline-secondary" />
        </div>
    </form>
</div>

CourseProjectItr/Views/User/Index.cshtml
@model CourseProjectItr.Models.User
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewBag.Title = Localizer["Title"];
}

<link rel="stylesheet" href="~/css/userPage.css" />

<div class="mainfield">
    <h1>@Model.NickName</h1>
    <h2 class="text-muted">@ViewBag.Role</h2>
        <div class="create-button">
            <a class="btn btn-sm btn-success" asp-controller="Collection" asp-action="Collection" asp-route-userID="@Model.Id">@Localizer["Create"]</a>
        </div>
</div>
<hr />
<div class="flex-container">
    <div class="box-1">
        <table>
            <tbody>
                <tr><th>@Localizer["Email"]:</th><td>@Model.Email</td></tr>
                <tr><th>@Localizer["FirstName"]:</th><td>@Model.FirstName</td></tr>
                <tr><th>@Localizer["LastName"]:</th><td>@Model.LastName</td></tr>
                <tr><th>@Localizer["Age"]:</th><td>@Model.Age</td></tr>
                <tr><th>@Localizer["Register"]:</th><td>@Model.RegisterDate</td></tr>
                <tr><th>@Localizer["LastLogin"]:</th><td>@Model.LastLogin</td></tr>
            </tbody>
        </table>
        <div class="edit-button">
            <a class="btn btn-lg btn-block btn-primary" asp-controller="User" asp-action="Edit" asp-route-id="@Model.Id" type="submit">@Localizer["Edit"]</a>
            @if (ViewBag.Role == "admin" || ViewBag.Role == "author")
            {
                <a class="btn btn-lg btn-block btn-primary" asp-controller="User" asp-action="AdminList" type="submit">@Localizer["Admin"]</a>
            }
        </div>
    </div>
    <div class="box-2">
        <form>
            <div class="row">
                @foreach (var collection in ViewBag.Collection)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            @if (collection.ImageUrl != null)
                            {
                                <img src="@Url.Content(collection.ImageUrl)" alt="Image" style="width: 100%;max-height: 300px;" />
                            }
                            <div class="card-body">
                                <h3 class="card-text">@collection.Name</h3>
                                <p class="card-text">@collection.Review</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a asp-controller="Collection" asp-action="ItemList" asp-route-collectionId="@collection.Id"
                                           asp-route-userID="@Model.Id" type="button" class="btn btn-sm btn-outline-secondary">@Localizer["Open"]</a>
                                        <a asp-controller="Collection" asp-action="Edit" asp-route-Id="@collection.Id"
                                           asp-route-userName="@User.Identity.Name" type="button" class="btn btn-sm btn-outline-secondary">@Localizer["EditCol"]</a>
                                        <a asp-controller="Collection" asp-action="Delete" asp-route-collectionId="@collection.Id"
                                           asp-route-userName="@Model.UserName" type="button" class="btn btn-sm btn-outline-secondary">@Localizer["Delete"]</a>
                                    </div>
                                    <small class="text-muted">@collection.Theme</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </form>
    </div>
</div>